apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component--mtfj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component--mtfj
    app.kubernetes.io/part-of: test-app-ornc
  name: test-component--mtfj
  namespace: e2e-test-pipelines-zizg
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: test-component--mtfj
status:
  loadBalancer: {}
